# coding: utf-8

# Contient la liste des expressions.
s_ListeExpressions = [
    "Aller à quelqu’un comme un gant",
    "Appeler un chat un chat",
    "Après la pluie, le beau temps",
    "Au bout de son rouleau",
    "Au bout du tunnel",
    "Au pied de la lettre",
    "Au royaume des aveugles, les borgnes sont rois",
    "Autant chercher une aiguille dans une botte de foin",
    "Avoir bon pied bon œil",
    "Avoir des fourmis dans les jambes",
    "Avoir du front tout le tour de la tête",
    "Avoir du pain sur la planche",
    "Avoir l’estomac dans les talons",
    "Avoir l’oreille fine",
    "Avoir la chair de poule",
    "Avoir la grosse tête",
    "Avoir le beurre et l’argent du beurre",
    "Avoir le compas dans l’œil",
    "Bavard comme une pie",
    "Bayer aux corneilles/Bâiller à s’en décrocher la mâchoire",
    "Boire comme une éponge",
    "Bouche cousue!",
    "C’est du gâteau.",
    "C’est en forgeant qu’on devient forgeron",
    "C’est là où le bât blesse",
    "Casser les pieds à quelqu’un",
    "Changer un cheval borgne pour un cheval aveugle",
    "De fil en aiguille",
    "Débarrasser le plancher",
    "Dévoiler le pot aux roses",
    "Donner un coup de poignard dans le dos",
    "En avril, ne te découvre pas d’un fil; en mai, fais ce qu’il te plaît",
    "En faire tout un plat",
    "Enfoncer une porte ouverte",
    "Être comme les deux doigts de la main",
    "Être dans une impasse",
    "Être la cinquième roue du carrosse",
    "Être né sous une bonne étoile",
    "Faire chou blanc",
    "Faire contre mauvaise fortune bon cœur",
    "Faire d’une pierre deux coups",
    "Faire des yeux de velours à quelqu’un",
    "Faire la pluie et le beau temps",
    "Faire mouche",
    "Fermer les yeux sur quelque chose",
    "Gai comme un pinson",
    "Humeur de chien",
    "Il n’y a pas de fumée sans feu",
    "Il pleut/tombe des clous",
    "Il y a anguille sous roche",
    "Jeter l’argent par les fenêtres",
    "Les cordonniers sont toujours les plus mal chaussés",
    "Marcher comme sur des roulettes",
    "Mettre des bâtons dans les roues",
    "Mettre la puce à l’oreille",
    "Mettre le doigt sur quelque chose",
    "Mettre tous ses œufs dans le même panier",
    "Mon petit doigt me l’a dit",
    "Ne pas avoir la langue dans sa poche",
    "Ne pas y aller par quatre chemins",
    "Ne tenir qu’à un fil",
    "Passer l’éponge sur quelque chose",
    "Payer rubis sur l’ongle",
    "Quand on parle du loup, on en voit la queue",
    "Qui se ressemble s’assemble",
    "Rendre la monnaie de sa pièce",
    "Se cogner/Se taper la tête contre les murs",
    "Se jeter dans la gueule du loup",
    "Taper dans le mille",
    "Tâter le terrain",
    "Tendre l’autre joue",
    "Tenir le crachoir",
    "Tirer son chapeau à quelqu’un",
    "Tiré à quatre épingles",
    "Toucher du bois",
    "Tourner autour du pot",
    "Un tiens vaut mieux que deux tu l’auras",
]