# Generated by Django 2.2.5 on 2019-10-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchettes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchette',
            name='status_buchette',
            field=models.CharField(choices=[('D', 'Demande de Buchette en cours'), ('A', 'Buchette acceptée par le comité'), ('S', 'Buchette soldée'), ('R', 'Buchette refusée par le comité')], default='D', max_length=1),
        ),
    ]
