# Generated by Django 2.2.5 on 2019-10-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchettes_app', '0004_auto_20191021_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchette',
            name='message_defence',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='buchette',
            name='status_buchette',
            field=models.CharField(choices=[('D', 'Demande de Buchette en effectuée'), ('E', "L'accusé a écrit sa défence"), ('A', 'Buchette acceptée par le comité'), ('P', 'Buchette payée en attente de validation'), ('V', 'Paiement de la buchette validée par 1 utilisateur'), ('S', 'Buchette soldée'), ('R', 'Buchette refusée par le comité')], default='D', max_length=1),
        ),
    ]
