# Generated by Django 2.2.5 on 2019-10-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buchettes_app', '0005_auto_20191028_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buchette',
            old_name='message_defence',
            new_name='message_defense',
        ),
    ]
