# Generated by Django 2.2.5 on 2019-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchettes_app', '0006_auto_20191028_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchette',
            name='temps_restant',
            field=models.TimeField(default='00:00'),
        ),
    ]
