# Generated by Django 2.2.5 on 2019-10-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchettes_app', '0007_buchette_temps_restant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchette',
            name='temps_restant',
            field=models.DurationField(default='00:00'),
        ),
    ]
