# Generated by Django 2.2.5 on 2019-10-29 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchettes_app', '0008_auto_20191029_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchette',
            name='temps_restant',
            field=models.DurationField(default=datetime.timedelta(0, 57)),
        ),
    ]
