# Generated by Django 2.2.5 on 2019-10-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buchettes_app', '0009_auto_20191029_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buchette',
            name='temps_restant',
        ),
    ]
