# Generated by Django 2.2.5 on 2019-10-29 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchettes_app', '0010_remove_buchette_temps_restant'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchette',
            name='temps_restant',
            field=models.DurationField(default=datetime.timedelta(0, 57)),
        ),
    ]
