# Generated by Django 2.2.5 on 2019-10-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchettes_app', '0011_buchette_temps_restant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchette',
            name='status_buchette',
            field=models.CharField(choices=[('D', 'Demande de Buchette en effectuée'), ('E', "L'accusé a écrit sa défence"), ('A', 'Buchette acceptée par le comité'), ('P', 'Buchette payée en attente de validation'), ('S', 'Buchette soldée'), ('R', 'Buchette refusée par le comité')], default='D', max_length=1),
        ),
    ]
