# Generated by Django 2.2.5 on 2019-11-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchettes_app', '0012_auto_20191029_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchette',
            name='nom_membre_comite',
            field=models.TextField(default=''),
        ),
    ]
