# Generated by Django 2.2.5 on 2019-11-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchettes_app', '0013_buchette_nom_membre_comite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchette',
            name='message_buchette',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='buchette',
            name='message_defense',
            field=models.TextField(default='', max_length=300),
        ),
    ]
