# Generated by Django 3.0.6 on 2020-05-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchettes_app', '0014_auto_20191108_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchette',
            name='vote_contre',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buchette',
            name='vote_pour',
            field=models.IntegerField(default=0),
        ),
    ]
